### PR TITLE
Added scrollable style `focused` to be displayed when mouse is over the scrollable area

### PR DESCRIPTION
**Pull request by GyulyVGC**
Hi! It's my first PR here for iced!

I added a style `focused` thought to be displayed when the scrollable area is hovered (not the scrollbar itself).

In my opinion, this is a more flexible solution to #1573.
In this way, a user can decide to hide the scroller when the area is not hovered or simply to have a different style from the `active` case, which would now be used when the scrollable area is not hovered.
If `focused` is not implemented, `active` will be used anyway.

If you don't like the name "focused", suggestions are welcomed!

https://user-images.githubusercontent.com/100347457/214104009-cbd3a5d6-336a-4478-9fd4-879c2059bb70.mp4

### CODE REVIEW

**Review by hecrj — CHANGES_REQUESTED** [review]
I think the name should be `hovered` instead of `focused`, like in a `button::StyleSheet`.

**Comment by GyulyVGC** [comment]
> I think the name should be `hovered` instead of `focused`, like in a `button::StyleSheet`.

The point is that `hovered` is already used to refer to the case when just the Scrollbar is hovered (instead of the whole scrollable area).

**Comment by GyulyVGC** [comment]
@hecrj may I ask you what can I do to make this PR ready to be merged?

**Comment by hecrj** [comment]
@GyulyVGC We need a better name here. `focused` is misleading.

**Comment by GyulyVGC** [comment]
You are free to suggest a name of your preference. 

Hovered would be awesome, but the problem is that it's already used.

**Comment by hecrj** [comment]
I think we could just add a boolean `over_scrollbar` argument to the `hovered` method.

**Comment by GyulyVGC** [comment]
> I think we could just add a boolean `over_scrollbar` argument to the `hovered` method.

Wouldn't this method also require to pass two distinct `style` arguments?

**Comment by hecrj** [comment]
> Wouldn't this method also require to pass two distinct style arguments?

No. The `Style` is always the same for both states of the scrollable.

**Comment by GyulyVGC** [comment]
> I think the name should be `hovered` instead of `focused`, like in a `button::StyleSheet`.

Following your suggestion, I renamed it to `hovered`. 
The style that was previously `hovered` has been renamed to `hovered_scrollbar`.

**Review by hecrj — APPROVED** [review]
Thanks!

I just added the `is_mouse_over_scrollbar` flag as I suggested in the end.

**Comment by GyulyVGC** [comment]
Amazing! Thanks for the corrections!

**Pull request merged**
