### PR TITLE
Simplify code, avoid unstable function

### PR DESCRIPTION
**Pull request by nilsmartel**
Makes code more obvious by reducing usage of an uncommon macro and an unstable feature.

While this is a tiny change, I believe it's nicer to use "more standard" (e.g. more common) code. I always like to believe obvious code should be preferred, especially when coding as a community.

Here we sacrifice close to nothing in terms of character count, while avoiding the use of an uncommonly used macro (avoiding this pattern is a personal opinion)
and avoiding an _unstable_ standard-library feature: https://doc.rust-lang.org/std/primitive.bool.html#method.then_some

### CODE REVIEW

**Comment by Niedzwiedzw** [comment]
`matches!` is unstable?

**Comment by geom3trik** [comment]
No, they are referring to the `then_some` method for bool, but actually it's only the const version which is unstable. Also I don't think the `matches!` macro is that uncommon personally.

**Review by 13r0ck — APPROVED** [review]

**Comment by nilsmartel** [comment]
I personally think there are very few and narrow cases, where matches! Should be preferred over match, especially since we would only ever safe  3-5 characters every now and  then while invoking some macro to avoid a feature that is as fundamental as the if statement.

More importantly I think matches! should never be used where == can be applied

**Comment by fu5ha** [comment]
Clippy would disagree :P https://rust-lang.github.io/rust-clippy/master/#match_like_matches_macro though of course cilppy is not necessary the arbiter of all that is right in the world, it does show general community sentiment

**Comment by nilsmartel** [comment]
That is a good hint, though this specific lint would not apply for the proposed code changes.

**Review by hecrj — COMMENTED** [review]
I think these changes are fairly subjective and do not warrant a discussion.

**Pull request closed without merging**
