### PR TITLE
Fixed Operations within PaneGrid

### LINKED ISSUE #1532: Operations Broken in PaneGrid
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When the target of an [Operation](https://github.com/iced-rs/iced/pull/1399) lies anywhere within a `PaneGrid`, the operation is silently ignored.

You can reproduce the issue by running this [modified example](https://github.com/iced-rs/iced/commit/4c4105fdfbbb0f98fb160fdc76d68da4395d4797).
I've added a 'snapTo 0.0' whenever you click a Pane, so you can:
1. You can resize the window such that the scrollbar appears
2. Scroll that bar down a bit.
3. Then, clicking anywhere in any pane **should** cause all scrollbars to snap to the top (but doesn't without the fix))

_Note: I removed the `responsive` part of the example for this reproduction, because it also breaks Operations. I'll open a separate issue for that._

I think the fix is pretty straightforward (`PaneGrid` is simply missing its `operate` method), so I'll put out a PR for this shortly.

### What is the expected behavior?

Operations should work within PaneGrids

### Version

master

### Operative System

Windows

### Do you have any log output?

_No response_

### PR DESCRIPTION
**Pull request by rs017991**
Fixes #1532

### CODE REVIEW

**Comment by rs017991** [comment]
Oops, I missed a file when committing. Coming right up...

**Comment by hecrj** [comment]
No worries! Just fixed implemented the missing stuff myself :)

**Comment by rs017991** [comment]
Ah, you beat me to it. Sorry about that

**Review by hecrj — APPROVED** [review]
No worries! I had the feeling I missed some stuff here. Thanks for cathing it!

**Pull request merged**
