### PR TITLE
Make `overlay::menu` accessible

### LINKED ISSUE #1406: No way to access `menu::Stylesheet`
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

On the current master branch, there is no way to access the `menu::StyleSheet` from `iced` itself, so you can't implement theming for a picklist without pulling in `iced_style` manually.

### What is the expected behavior?

There should be a `menu` mod or something in `iced`. 

### Version

master

### Operative System

Windows

### Do you have any log output?

_No response_

### PR DESCRIPTION
**Pull request by 0x192**
Implementing `pick_list::StyleSheet` for a custom `Theme` requires to also implement `menu::StyleSheet` which is currently not accessible.

This pull request creates an alias of `overlay::menu` in the root so you can import it with `use iced::overlay::menu`.

Fixes #1406

### CODE REVIEW

**Comment by 0x192** [comment]
Note sure about the `improvement` label. It's more of a `bugfix` of than an `improvement`.

#1362 introduced the theme support allowing to implement a custom style for all widgets except the `pick_list` because you need to implement `menu::stylesheet` which is not accessible.

**Review by hecrj — APPROVED** [review]
Thanks! :tada:

**Comment by 0x192** [comment]
Thanks to you!

Why did you need to add this? I'm not sure to understand

```rust
pub type Element<'a, Message, Renderer = crate::Renderer> =
    iced_native::overlay::Element<'a, Message, Renderer>;
``` 

(no problem if you don't have time to answer)

**Comment by hecrj** [comment]
Just figured we should expose `overlay::Element` as well, since we are exposing `overlay::Menu` an it is part of its public API.

**Pull request merged**
