### PR TITLE
basic IME supporting

### LINKED ISSUE #979: IME input method on iced application (fcitix on linux)
Hi,

is there a plan to support input method on linux for iced application?

The current state of iced example looks like this:

 

The input method (fcitix)'s panel does not follow the cursor.

Possible way to do is via XIM in linux?

### PR DESCRIPTION
**Pull request by t18b219k**
# General
This PR fix #979,#1544. 
iced ime support was broken due to winit 0.27 update .
This PR add event to fit new winit IME event model and introduce new event support for text_input.  

## how to test
 download app from my repo https://github.com/t18b219k/iced_text_input_sample/
### tested on
- [x] windows MS-IME
- [x] windows Google IME
- [x] linux ibus x11
- [x] linux ibus wayland(gnome/kde)
- [x] linux fcitx x11
- [x] linux fcitx wayland(gnome/kde/sway/hyprland)
- [x] macos IME

## Phase 2 : Candidate position is near the TextInput?
You maybe failed to reproduce due to IME version.
candidate positon on X11 require LibX11 1.8.2 or above.
### Wayland requirement.
 * input_method_popups_v2

## tested on
- [x] windows MS-IME 
- [x] windows Google IME
- [x] Linux IBus X11(on Manjaro 22.0)
- [x] Linux IBus gnome wayland
- [x] Linux Fcitx5 X11(on Manjaro 22.0)
- [x] Linux Fcitx5 gnome wayland
- [x] Linux Fcitx5 kde wayland( can't move to the position ) 
- [x] Linux Fcitx5 sway(supported on sway-im AUR package.) 
- [x] Linux Fcitx5 hyprland
- [x] macos IME(setting candidate window position delay. maybe macos issue?)

### behavior
https://user-images.githubusercontent.com/48007646/205664366-ea71ddaf-a778-4f1a-9d0e-1b5cb557e70c.mp4
### test 
 not required.
We render underline and cursor correctly if winit correctly report it.
- [x] windows
- [x] macos google japanese IME(not report boldlining),
- [x] macos pinyin  
- [x] IBus X11 (no boldlining)
- [x] IBus gnome Wayland(pinyin,mozc,and anthy incorrect report)
- [x] Fcitx5 X11 (no boldlining)
- [x] Fcitx5 gnome Wayland (mozc and anthy incorrect event report)
- [x] Fcitx5 sway 
- [x] Fcitx5 hyprland 
- [x] Fcitx5 kde Wayland 
## tasks

- [x] enable winit IME support
- [x] translate winit IME event to iced event
- [x] text_input editing support
- [x] tell IME to put candidate window
- [x] underline

### CODE REVIEW

**Comment by t18b219k** [comment]
I don't have apple devices please test someone .

**Comment by t18b219k** [comment]
we should move IME window to correct position to provide native look and feel
where we should implement this logic.

**Comment by t18b219k** [comment]
if alacritty  works well this should work as well.
please test alacritty works well.

**Comment by someoneinjd** [comment]
On my mac the candidate box is showing but it's in the wrong place (macOS Monterey 12.6, MacBook Pro (16-inch, 2019))
截屏2022-10-18 14 20 09
In alacritty it works well. (alacritty 0.11.0)
截屏2022-10-18 14 26 31

**Comment by t18b219k** [comment]
we need to tell IME candidate window position to winit but I can't find good way.

**Comment by t18b219k** [comment]
@hecrj  I want to move IME candidate window to correct position but I can't find the way to send window Action from widget.
I think we need to extend Widget interface like clipboard implementation.
Is there any opinion to this problem.

**Comment by t18b219k** [comment]
now candidate window placed near TextInput .
this positioning is not best but much better than nothing,

**Comment by t18b219k** [comment]
@Cupnfish @someoneinjd  please test candidate window position is correct.

**Comment by someoneinjd** [comment]
Thanks for your hard work. It works in most cases. But when I use the input method for the first time since the application started, the position is wrong, and after that the position is correct.
截屏2022-10-20 20 34 49
截屏2022-10-20 20 35 02
Alacritty also has this problem, so it might be a winit problem?
截屏2022-10-20 20 35 45
截屏2022-10-20 20 35 56

**Comment by Cupnfish** [comment]
> Thanks for your hard work. It works in most cases. But when I use the input method for the first time since the application started, the position is wrong, and after that the position is correct. 截屏2022-10-20 20 34 49 截屏2022-10-20 20 35 02 Alacritty also has this problem, so it might be a winit problem? 截屏2022-10-20 20 35 45 截屏2022-10-20 20 35 56

This is also the case on my laptop. Not only that, switching to another app and then switching back triggers the bug again.

**Comment by t18b219k** [comment]
Maybe we need to notify IMEEnabled Event from IME to TextInput .
I will try to fix this problem today .

**Comment by t18b219k** [comment]
@Cupnfish  @someoneinjd  please test condidate window is correct position even first time.

**Comment by t18b219k** [comment]
if we set IME position when we receive click event waybe we can achieve correct positioning.

**Comment by t18b219k** [comment]
@someoneinjd  @Cupnfish
 please test if it works. 
set_ime_position when TextInput clicked.
If this doesn't work we need to talk with alacritty team.

**Comment by Cupnfish** [comment]
> @someoneinjd @Cupnfish please test if it works. set_ime_position when TextInput clicked. If this doesn't work we need to talk with alacritty team.

It still comes up with that problem.

**Comment by someoneinjd** [comment]
Unfortunately the problem still exists
截屏2022-10-22 07 44 51

**Comment by t18b219k** [comment]
shall we release this PR or not.
if you fixed this problem please open PR to mine repo.

**Comment by someoneinjd** [comment]
I find that `set_ime_position` in IMEEnabled doesn't work, maybe we need to set the candidate box position before receiving this event.
But this may not be easy to achieve, because when I use the Chinese input method to start todos and type, `IMEEnabled` is the first event received by the `update` function.

**Comment by zmtq05** [comment]
image

Unfocus text_input then type korean, preedit character(expect) inserted in text_input.
It can delete manually but isn't deleted automatically.

Used font: [NanumGothic.ttf](https://hangeul.naver.com/font/nanum)
OS: Windows 10

**Comment by t18b219k** [comment]
IME handling is very platform dependent issue so feel free to PR to my repo .

**Comment by t18b219k** [comment]
@hecrj 
This PR is very platform issue but no one tried to improving this PR.
I think it better to basic support than nothing.

**Comment by zmtq05** [comment]
I want to help, but I don't know where to start. Can I get a hint?

**Comment by t18b219k** [comment]
@zmtq05 
here is my repo https://github.com/t18b219k/iced 
it seems to me connecting to IME is ok .
so I want to you to dive to native/src/widget/text_input.rs update function.
before you making PR please run CI to build test binary.
if you can please install CJK font for easy test.

**Comment by zmtq05** [comment]
I resolve my issue by does nothing when receive preedit event and unfocused.
but japanese and chinese candidate window still appear when unfocused then input.

sorry for bad english.

**Comment by icedrocket** [comment]
I'm concerned about the case where the string contains a variation selector when input with the IME. It seems iced doesn't handle the variation selector at all.

**Comment by t18b219k** [comment]
I will resolve X11 issue by directly talk to ibus and fcitx  using dbus API.

**Comment by Riey** [comment]
> Thanks for your hard work. It works in most cases. But when I use the input method for the first time since the application started, the position is wrong, and after that the position is correct.
> 截屏2022-10-20 20 34 49
> 截屏2022-10-20 20 35 02
> Alacritty also has this problem, so it might be a winit problem?
> 截屏2022-10-20 20 35 45
> 截屏2022-10-20 20 35 56
> 

Related X11 bug

https://bugs.freedesktop.org/show_bug.cgi?id=1580

**Comment by t18b219k** [comment]
directory talk to ibus and fcitx is not easy.
I'm now improving looking.

**Comment by t18b219k** [comment]
underlining when using IME.
Bold line means this section text is converting.

https://user-images.githubusercontent.com/48007646/198844635-dd08f4e4-47b4-4ec2-8a3f-d580096cc5f4.mp4

**Comment by t18b219k** [comment]
@zmtq05 Thank you for good idea.
My implementation is buggy when we use IME and open many TextInputs.
Your idea implemented in my latest patch.
 https://github.com/t18b219k/iced/commit/fbc9c595c994831e4c18030b4d9d09a2bea3a516

**Comment by zmtq05** [comment]
underline position is weird.
image

**Comment by zmtq05** [comment]
image
Cursor must be located after the character.
image

**Comment by t18b219k** [comment]
There is no IME event standard even in MS.
Korean always returns indicator position 0,0 means cursor should place before editing character but Japanese and Chinese IME returns correctly.

**Comment by t18b219k** [comment]
ibus-hangul returns correctly.
ibus-pinyin same as MS Korean but correctly report.
if we apply MS Korean will break ibus-pinyin.

**Comment by zmtq05** [comment]
```diff
diff --git a/native/src/widget/text_input/ime_range.rs b/native/src/widget/text_input/ime_range.rs
index f66b8f72..a31eaef4 100644
--- a/native/src/widget/text_input/ime_range.rs
+++ b/native/src/widget/text_input/ime_range.rs
@@ -55,6 +55,8 @@ impl IMERange {
         if let Some((start, end)) = self.bold_line_range {
             if end == text.len() {
                 Some(text)
+            } else if start == 0 && end == 0 {
+                Some(text.split_at(end).1)
             } else if end == start {
                 Some(text.split_at(end).0)
             } else {
```

I fixed issue by this. Could you test japanese and chinese?

**Comment by t18b219k** [comment]
My developing branch is ime_support.
same Korean fix implemented in ime_support branch.
your impl not break JP and pinyin but not tested on chewing.

**Comment by t18b219k** [comment]
@hecrj please merge winit 0.27.5 to support candidate window position on x11 platform.

candidate window position setting works on fcitx5 5.0.19 + winit 0.27.5.
but not works on winit 0.27.2.

**Comment by t18b219k** [comment]
X11 and Wayland IME issue will fixed by using ibus directly.
I'm implementing winit patch to use ibus .

**Comment by t18b219k** [comment]
@hecrj 
I did best but there is bug in Desktop enviroment but current iced text_input status is same as alacritty and also better than egui.

**Comment by zmtq05** [comment]
image
Cursor position issue again. :joy:

**Comment by t18b219k** [comment]
maybe reintroduced by merge conflict resolve or IMEState refactoring.

**Comment by t18b219k** [comment]
please someone test macos japanese IME to find bug in underline.

**Comment by t18b219k** [comment]
@Cupnfish 
I made some change to this PR.
please test underlining if you can input Japanese please test it.

**Comment by Drodofsky** [comment]
Phase 1 and 3 works. But phase 2 doesn't work. The candidate position is below the window. I am using the latest release of Pop OS with MOZC-ibus.

**Comment by t18b219k** [comment]
@someoneinjd @Cupnfish 
IME enable and disable logic changed to support Password input .
Windows and linux works correctly but macos is correctly working?

**Comment by someoneinjd** [comment]
https://user-images.githubusercontent.com/61791143/206238705-05654eb8-8303-4ca4-b69c-d4a68c5613f9.mov

looks like it works fine on intel macOS Ventura 13.0.1

**Comment by Drodofsky** [comment]
I am using the latest version of Pop os with Mozc-ibus (version 2.26.4220.102) as the input method.
Screenshot from 2022-12-11 00-47-18

**Comment by t18b219k** [comment]
@Drodofsky 
IBus mozc can display preedit but can't move Candidate window near the TextInput due to libx11 limitation.
[very recently libx11 merge request](https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/127)  enable placing candidate window to  user specified position.  but ibus ,fcitx, and winit update needed to support it.

**Comment by t18b219k** [comment]
@Drodofsky 
if you can try Manjaro , this issue fixed but unfortunately no ibus-mozc only ibus-anthy.

**Comment by Drodofsky** [comment]
> @Drodofsky if you can try Manjaro , this issue fixed but unfortunately no ibus-mozc only ibus-anthy.

Thank you. It works on Wayland. Unfortunately, Wayland is not yet stable on Pop os.

**Comment by Drodofsky** [comment]
Closes #1544

**Comment by t18b219k** [comment]
fortunately close bug #1544 but why #1544 closed?

**Comment by Drodofsky** [comment]
Winit generates no event when you hit ^, and IME is disabled.

**Comment by AllenDang** [comment]
This is the PR I'm waited for soooooo long! Iced could become a solid GUI framework after this is merged.

**Comment by t18b219k** [comment]
@someoneinjd 
some changes may affect to macos so we need to test.
I have question about Sway.
* how to display candidate window?

**Comment by someoneinjd** [comment]
https://user-images.githubusercontent.com/61791143/209459596-19f33056-316c-45c6-9813-9236aa110542.mov

works fine!
AFAIK, displaying the candidate window requires the wayland server to support `input_method_popups v2`, which is not supported by Sway. [#7266](https://github.com/swaywm/sway/pull/7226) tries to add support for it. So you can build sway from this source or just install the aur package [sway-im](https://aur.archlinux.org/packages/sway-im). 
What's more, [hyprland](https://github.com/hyprwm/Hyprland) also supports `input_method_popups v2`, you can use it to test.

**Comment by t18b219k** [comment]
thanks for testing

**Comment by t18b219k** [comment]
due to very large change made in advanced text so I rebased .

**Pull request closed without merging**
