### PR TITLE
Provide native window access, via "fetch_native_handle" method on window.

### PR DESCRIPTION
**Pull request by dtzxporter**
This should alleviate some of the concerns in: https://github.com/iced-rs/iced/pull/2194#issuecomment-1888517346 because it will force the callback to be ran in the event loop in iced, and gives us a reference to the window directly instead. While the user _could_ mess up the iced state by making changes here, I think that anyone using this method should know what they are doing and it's an advanced use case.

Links:
#2194

### CODE REVIEW

**Comment by dtzxporter** [comment]
Will rework this once #2191 lands.

**Review by hecrj — APPROVED** [review]
Thanks!

**Comment by hecrj** [comment]
You call `as_raw`, then pattern match on `Wayland`, and you keep going from there.

https://docs.rs/iced/latest/iced/widget/shader/wgpu/rwh/enum.RawWindowHandle.html#variant.Wayland

**Comment by WhyNotHugo** [comment]
I looked at that before asking here, but that variant's associated type is:

```
pub struct WaylandWindowHandle {
    pub surface: NonNull<c_void>,
}
```

I'm not sure how to operate on a `c_void` (which is basically a type-erased pointer). Can't this actually be a reference with a proper type instead?

**Pull request merged**
