### PR TITLE
Release `0.4` — Stateless widgets, component trait, responsive views, WebGL support, and more!

### PR DESCRIPTION
**Pull request by hecrj**
<p align="center">
  <a href="https://github.com/greatest-ape/OctaSine">
    OctaSine
  </a>
  <a href="https://github.com/0x192/universal-android-debloater">
    Universal Android Debloater
  </a>
  <a href="https://github.com/ZakisM/bl3_save_edit">
    Borderlands 3 Save Edtor
  </a>
</p>

> Iced is an _experimental_ cross-platform GUI library for Rust focused on simplicity and type-safety. Inspired by [Elm].

This PR marks the end of the [`0.4.0` milestone] and the launch of a new release :rocket:

[Elm]: https://elm-lang.org/
[`0.4.0` milestone]: https://github.com/iced-rs/iced/milestone/7

# New features

- __[Stateless widgets][stateless]__ (#1284)  
  A brand new widget API that removes the need to keep track of internal widget state. No more `button::State` in your application!

- __[`Component` trait][component]__ (#1131)  
  A new trait to implement custom widgets with internal mutable state while using composition and [The Elm Architecture].

- __[`Responsive` widget][responsive]__ (#1193)  
  A widget that is aware of its dimensions and can be used to easily build responsive user interfaces.

- __[Experimental WebGL support][webgl]__ (#1096)  
  Applications can now be rendered into an HTML `canvas` when targeting Wasm by leveraging the WebGL support in [`wgpu`]. Thanks to @pacmancoder and @kaimast!

- __[Support for Raspberry Pis and older devices][raspberry]__ (#1160)  
  The compatibility of our OpenGL renderer has been improved and should run on any hardware that supports OpenGL 3.0+ or OpenGL ES 2.0+. Additionally, we started maintaining [Docker images for `aarch64` and `armv7`](https://github.com/orgs/iced-rs/packages) to easily cross-compile `iced` applications and target Raspberry Pis. Thanks to @derezzedex!

- __[Simpler `Renderer` APIs][renderer_apis]__ (#1110)  
  The surface of the `Renderer` APIs of the library has been considerably reduced. Instead of a `Renderer` trait per widget, now there are only 3 traits that are reused by all the widgets.

[webgl]: https://github.com/iced-rs/iced/pull/1096
[renderer_apis]: https://github.com/iced-rs/iced/pull/1110
[component]: https://github.com/iced-rs/iced/pull/1131
[raspberry]: https://github.com/iced-rs/iced/pull/1160
[responsive]: https://github.com/iced-rs/iced/pull/1193
[stateless]: https://github.com/iced-rs/iced/pull/1284
[The Elm Architecture]: https://guide.elm-lang.org/architecture/
[`wgpu`]: https://github.com/gfx-rs/wgpu

# Showcase

During this last year, many awesome applications have been created with iced! As I do in every release, I would like to highlight some of the _coolest_ ones:

- __[Borderlands 3 Save Editor]__, a tool to help you modify your Borderlands 3 Saves and Profiles.
- __[ENSnano]__, a 3D graphical application for DNA nanostructures.
- __[Lembas]__, a plugin management tool completely written in Rust for the game "Lord of the Rings Online".
- __[Linkage]__, a desktop typing tutor.
- __[OctaSine]__, a VST2 frequency modulation synthesizer written in Rust.
- __[Offline Chess Puzzles]__, a tool to view and solve puzzles from the Lichess puzzle database.
- __[PWDuck]__, a little duck :duck: protecting your passwords.
- __[Töörö Editor]__, a cross-platform sound editor for the [Fred's Lab Töörö] hardware synthesizer.
- __[Universal Android Debloater]__, a cross-platform GUI written in Rust using ADB to debloat non-rooted Android devices.

And there are more! Check out our [Project Showcase].

[Borderlands 3 Save Editor]: https://github.com/ZakisM/bl3_save_edit
[ENSnano]: https://github.com/thenlevy/ensnano
[Lembas]: https://github.com/mawilms/lembas
[Linkage]: https://github.com/linkage-rs/linkage
[OctaSine]: https://github.com/greatest-ape/OctaSine
[Offline Chess Puzzles]: https://github.com/brianch/offline-chess-puzzles
[PWDuck]: https://github.com/Kaiden42/PWDuck
[Töörö Editor]: https://github.com/sourcebox/tooro-editor
[Universal Android Debloater]: https://github.com/0x192/universal-android-debloater
[Project Showcase]: https://github.com/hecrj/iced/issues/355
[Fred's Lab Töörö]: https://fredslab.net/en/tooro-module.php

# Community
Since the last release, we have also started setting up the foundations for our open-source community.

We created [a GitHub organization][iced-rs] to centralize all of the core pieces of the project and adopt other important parts of the ecosystem that can be officially maintained by the community. So far, we have adopted two crates:

- [`iced_audio`], useful widgets for audio applications such as VST / LV2 plugins.
- [`iced_aw`], additional widgets for the library.

We also migrated from our old Zulip instance to [a new Discord server][discord], where we hold meetings regularly to review and coordinate work. These meetings have been quite successful so far! Feel free to join them!

Finally, we are actively working on proper learning material and documentation. In that direction, we have [an official learning guide][guide] and [a new website][website] in the works.

[iced-rs]: https://github.com/iced-rs
[`iced_aw`]: https://github.com/iced-rs/iced_aw
[`iced_audio`]: https://github.com/iced-rs/iced_audio
[discord]: https://discord.gg/3xZJ65GAhd
[guide]: https://book.iced.rs
[website]: https://iced.rs

# Thank you! :tada:
Finally, I want to give my thanks to everyone that has contributed to this release:

- @0x192 implemented the `Default` trait for `pure::State` (#1298).
- @13r0ck added support for selecting a value of a `PickList` by scrolling (#872).
- @Ace4896 added placeholder support for the `PickList` widget (#888).
- @aentity fixed a bug causing high memory usage of the `Svg` widget (#952).
- @akavel implemented proper handling of Exif orientation for raster images in `iced_wgpu`.
- @akhilman fixed an issue with window transparency in `iced_glow` (#1021).
- @Alch-Emi introduced `ContentFit` support for the `Image` and `Svg` widgets (#1219).
- @AldoMX added a `select_all` method to `text_input::State` (#776).
- @AlisCode decoupled `image::Handle` from `iced_native` and lowered the trait bound of `text::Renderer::Font` (#1155).
- @AndiHofi allowed `Application::run` to return on native platforms (#1112).
- @ATiltedTree improved the compatibility of `iced_wgpu` by using the preferred texture format of the window surface (#978).
- @BillyDM
  - fixed `iced_wgpu` panicking when a `SwapChain` frame is outdated (#667), and
  - tweaked the default styling of the `Rule` widget (#994).
- @blefevre added support for asymmetrical padding (#630).
- @casperstorm implemented a `pure` version of the `Tooltip` widget (#1315).
- @Chiheisen
  - fixed the layout logic of `PickList` to respect custom fonts (#886), and
  - improved the layout logic of the `image::Viewer` widget (#885).
- @clarkmoody
  - added support for generic elements in the title bars of a `PaneGrid` (#892), and
  - introduced overlay support for the title bar of a `PaneGrid` (#920).
- @cmot17 fixed an issue with text selection in the `TextInput` widget (#1098).
- @cossonleo fixed the overlay position of the `Component` widget (#1205).
- @Cupnfish
  - fixed a typo in the documentation (#810),
  - and added a primary backend option to the `WGPU_BACKEND` environment variable (#876).
- @daladim added the iced logo to the documentation (#1147).
- @derezzedex added support for ARM devices and older hardware (#1160).
- @diegodox fixed a typo in the documentation of `canvas::Program` (#927).
- @Dispersia upgraded `wgpu` to `0.8` (#830).
- @EkardNT added support for `Sandbox` applications to quit gracefully (#1175).
- @feylinara fixed a memory leak in the `integration_opengl` example (#1181).
- @gonsor added `text_color` to the `Style` of a `Checkbox` (#1116).
- @Imberflur
  - upgraded `winit` to `0.25` (#919),
  - fixed a few links in the documentation (#1121), and
  - fixed the `hash_layout` implementation of the `Container` widget (#1140).
- @Kaiden42 implemented a `Toggler` widget (#535).
- @LordRatte updated links in  the documentation to point to the new `iced-rs` organization (#1168).
- @Luni-4
  - added executable permissions to the `todos` example in CI for macOS builds (#956), and
  - stopped the shell from opening on Windows (#1049).
- @marienz fixed `overlay` calls not being forwarded when using `Element::map` (#1294).
- @mettz fixed an incorrect color being used with `Element::explain` (#1109).
- @mtsr documented how to disable a `Button` (#646).
- @nicksenger
  - fixed the `Widget::height` implementation of the `Component` widget (#1149),
  - implemented `Widget::overlay` for `Component` (#1154),
  - fixed layout invalidation of nested components (#1169),
  - fixed the overlay layout for the `Responsive` widget (#1262),
  - fixed the diffing strategy for nested pure components (#1301),
  - fixed the diffing strategy for pure stateless components (#1309), and
  - fixed a panic when using a pure `Component` in a pure `Responsive` widget (#1319).
- @n8henrie fixed the path to `ferris.png` in the `tour` example (#1157).
- @oknozor fixed the visibility of the constants in the `blit` shader in `iced_wgpu` (#1084).
- @PolyMeilex
  - upgraded `wgpu` to `0.9` (#925),
  - upgraded `wgpu` to `0.10` (#1000), and
  - upgraded `wgpu` to `0.11` (#1081).
- @pacmancoder implemented experimental WebGL support in `iced_wgpu` (#1096).
- @RamType0 removed unnecessary `String` allocation in some examples (#1106).
- @RDambrosio016 fixed example links in the documentation to point to the latest release (#877).
- @sundy-li fixed the `README` of the `integration_opengl` example.
- @taiki_e enabled the `qr_code` feature in docs.rs (#815).
- @TannerRogalsky
  - disabled the default features in the `twox-hash` dependency (#1117)
  - fixed async traits for Wasm (#1118).
- @tarkah
  - added a new `Hidden` variant to `window::Mode` (#825),
  - introduced a new `Moved` variant to `window::Event` (#965),
  - fixed the overlays on a `PaneGrid` title bar not closing when dragging a pane (#971),
  - added a `Fill` variant for `Alignment` (#1044),
  - removed redundant `Slider` messages (#1114),
  - added a line dash API for the `Canvas` widget (#1225), and
  - fixed the text wrapping of the selected option of a `PickList` (#1318).
- @thenlevy
  - fixed the dimensions of `scissor_rect` in `iced_wgpu` being too large in some circumstances (#818), and
  - implemented event handling of the `Enter` key for `TextInput` (#1150).
- @ThisIsRex fixed the position of the handle and rail of a `Slider` (#1286).
- @traxys introduced a `window::Setting` to toggle drag and drop on Windows (#893).
- @xy37v replaced Zulip mentions in the `README` with the new Discord server (#1151).
- @yamadapc improved the support of `iced_glow` for multi-windowed applications (#980).
- @yusdacra
  - added methods to control a `Scrollable` programmatically (#607),
  - introduced a flag to toggle multithreaded rasterization of text primitives (#914), and
  - updated links in the documentation (#915).
- @ZakisM optimized the RGBA / BGRA conversion for vectorial images in `iced_wgpu` (#875).
- @zdevwu added `text_color` and `font` methods to `Radio` and `Checkbox` (#831).

I am very grateful for all your contributions. Thank you! :tada:

### CODE REVIEW

**Comment by TannerRogalsky** [comment]
Incredible release! Thank you for your work and congratulations! You should be very proud!

**Comment by greatest-ape** [comment]
Congratulations and thank you! 🥳 

It's really cool that you chose to feature OctaSine! There is a new release coming up soon, with a redesigned GUI. Here is a sneak peek ;-)

octasine-light

octasine-dark

**Comment by Luni-4** [comment]
What a great release! Thank you everyone for your work! :smiley:

**Comment by 0x192** [comment]
Big thank to all the contributors and a huge thank for the one and only @hecrj! Kudos for this release! :trophy:

I *really* wasn't ready to see this release featuring my side-project [Universal Android Debloater](https://github.com/0x192/universal-android-debloater). Thank you!

I also feel a bit illegitimate to appear in the contributors list simply because I implemented the `Default` trait for a struct. I'll try to tackle a real issue next time! :slightly_smiling_face:

**Pull request merged**
