### PR TITLE
Fix slider

### PR DESCRIPTION
**Pull request by wiiznokes**
attempt to fix https://github.com/pop-os/cosmic-settings/issues/628

currently, the grab handle seems a little off, but i'm not sure this is a layout  _bug_.

master
Capture d’écran du 2024-09-26 23-42-39
pr
Capture d’écran du 2024-09-26 23-43-42

### CODE REVIEW

**Comment by wiiznokes** [comment]
Hum, i'm starting to think its a cosmic only issue. Will see when they rebase they fork

**Comment by wiiznokes** [comment]
Initially, i wanted to fix a cosmic applet that use the slider from Iced
screenshot-2024-10-02-15-38-05
(only visible on hover)

but yeah, it will require more investigation from me. Sorry for the useless PR

**Comment by hecrj** [comment]
No worries!

**Comment by peterkrull** [comment]
I tried to bring this up [on discourse](https://discourse.iced.rs/t/making-slider-widget-follow-curser-more-accurately/521), but I guess not many people saw it. My suggestion is to have "saturation zones" at each end of the slider, where clicking that region would bring the slider to either 0% or 100%. The length of these regions would be equal to the half-width of the handle. So the slider would look the same as it does now, but the way it responds to events would be modified slightly.

**Pull request closed without merging**
