### PR TITLE
Logarithmic slider

### PR DESCRIPTION
**Pull request by GyulyVGC**
This PR introduces a function `logarithmic_scale()` to `slider` and `vertical_slider` to set the distribution of values of the slider range to logarithmic, instead of linear.

This is particularly useful in the case of very wide ranges for which is wanted to have a good precision in selecting the range lower values.

Of course, since the logarithm is not defined for non-positive numbers, it is meaningful to use this option only for ranges of values greater than zero.

Below an example of implementation.

https://user-images.githubusercontent.com/100347457/216378631-b8ed5637-b945-4464-a557-2fea7ab4f209.mp4

### CODE REVIEW

**Comment by hecrj** [comment]
Since the behavior seems different from a normal slider, I have a feeling that this should be a new widget with a new design as well.

**Comment by GyulyVGC** [comment]
> Since the behavior seems different from a normal slider, I have a feeling that this should be a new widget with a new design as well.

I don't feel this needing, if you think about it, it is still a slider just with a different values distribution.
Its behaviour is actually the same, but now the range is not linear but logarithmic.
Creating a new widget for it would mean to duplicate a lot of code, since I don't see how the design should be changed either.
If values in the range are expressed as power of ten (Kilo, Mega, Giga...or 10^2, 10^3...) as in my use case, its apparent behaviour would be exactly that of a standard slider. There are just context in which the linear scale is not appropriate.

Btw, I fixed the last clippy lints and now everything should pass.

Just let me know if for you it's good that in case the user sets a negative values range it panics or if in this case the `logarithmic_scale()` should have no effect (keeping it to linear even if this function is called).

**Comment by GyulyVGC** [comment]
> Since the behavior seems different from a normal slider, I have a feeling that this should be a new widget with a new design as well.

I don't feel this needing, if you think about it, it is still a slider just with a different values distribution.
Its behaviour is actually the same, but now the range is not linear but logarithmic.
Creating a new widget for it would mean to duplicate a lot of code, since I don't see how the design should be changed either.
If values in the range are expressed as power of ten (Kilo, Mega, Giga...or 10^2, 10^3...) as in my use case, its apparent behaviour would be exactly that of a standard slider. There are just context in which the linear scale is not appropriate.

Btw, I fixed the last clippy lints and now everything should pass.

Just let me know if for you it's good that in case the user sets a negative values range it panics or if in this case the `logarithmic_scale()` should have no effect (keeping it to linear even if this function is called).

**Comment by hojjatabdollahi** [comment]
We needed something like this to change audio volume. We just used a normal slider and added the log and power function when reading or setting the value. That enabled us to create different curves and find a natural response (slider to volume). So I don't think having this flag on slider would've helped us, as we needed to tweak the functions to get the best curve. Also, I don't think in most cases the user needs to know that the slider is logarithmic (they move the slider to the middle and expect the audio to feel half as loud), so a new widget for this with different UI may not be needed either. But this was just in our case, maybe there are other usecases that it makes sense to somehow tell the user that they are changing a logarithmic slider.

**Comment by hecrj** [comment]
I agree with @hojjatabdollahi in that this functionality seems quite specific to a particular use case. I would expect the user of the library to build it on top of the current slider.

**Pull request closed without merging**
