### PR TITLE
Fix Compiling of Download example

### PR DESCRIPTION
**Pull request by Vixea**

### CODE REVIEW

**Comment by hecrj** [comment]
All the examples are built in CI. This breaks the compilation instead of fixing it!

**Comment by Vixea** [comment]
```
error[E0308]: mismatched types
  --> src/main.rs:78:47
   |
78 |         let downloads = Column::with_children(self.downloads.iter().map(Download::view))
   |                         --------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Vec<Element<'_, _, _>>`, found `Map<Iter<'_, Download>, ...>`
   |                         |
   |                         arguments to this function are incorrect
   |
   = note: expected struct `Vec<iced_core::element::Element<'_, _, _>>`
              found struct `Map<Iter<'_, Download>, fn(&Download) -> Element<'a, Message, ...> {...::view}>`
```
then I have no clue why it doesn't build(latest rust version) running git iced

**Comment by hecrj** [comment]
You are not running the latest `iced`. Did you copy and paste the example code somewhere? Try `cargo update`.

**Comment by Vixea** [comment]
I did run `cargo clean` maybe forgot to run `cargo update` :sweat:

**Comment by Vixea** [comment]
umm well works now after fixing I brain fart but it should error now succeed instantly, which is what it does

**Pull request closed without merging**
